apiVersion: core.oxia.io/v1
kind: OxiaCluster
metadata:
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/managed-by: kustomize
  name: okk
  namespace: okk-workload
spec:
  image: oxia/oxia:latest
  coordinator:
    namespaces:
      - name: okk
        initialShardCount: 32
        replicationFactor: 3
        notificationsEnabled: true
  dataServer:
    replicas: 3