apiVersion: core.oxia.io/v1
kind: TestCase
metadata:
  name: tc-streaming-sequence-jvm-0
  namespace: okk
spec:
  type: streamingSequence
  duration: "24h"
  opRate: 100
  worker:
    image: oxia/okk-jvm-worker:main
    targetCluster:
      name: okk
      namespace: okk
