{{- if and .Values.pilot.enabled .Values.pilot.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: okk-pilot-secrets
  namespace: {{ include "okk.namespace" . }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.pilot.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
