// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: okk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Ok               Status = 0
	Status_AssertionFailure Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Ok",
		1: "AssertionFailure",
	}
	Status_value = map[string]int32{
		"Ok":               0,
		"AssertionFailure": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_okk_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_okk_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{0}
}

type Operation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Assertion *Assertion             `protobuf:"bytes,1,opt,name=assertion,proto3,oneof" json:"assertion,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Operation_Put
	//	*Operation_Delete
	//	*Operation_Get
	//	*Operation_List
	//	*Operation_Scan
	Operation     isOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_okk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetAssertion() *Assertion {
	if x != nil {
		return x.Assertion
	}
	return nil
}

func (x *Operation) GetOperation() isOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Operation) GetPut() *OperationPut {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Operation) GetDelete() *OperationDelete {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Operation) GetGet() *OperationGet {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Operation) GetList() *OperationList {
	if x != nil {
		if x, ok := x.Operation.(*Operation_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Operation) GetScan() *OperationScan {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_Put struct {
	Put *OperationPut `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type Operation_Delete struct {
	Delete *OperationDelete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type Operation_Get struct {
	Get *OperationGet `protobuf:"bytes,4,opt,name=get,proto3,oneof"`
}

type Operation_List struct {
	List *OperationList `protobuf:"bytes,5,opt,name=list,proto3,oneof"`
}

type Operation_Scan struct {
	Scan *OperationScan `protobuf:"bytes,6,opt,name=scan,proto3,oneof"`
}

func (*Operation_Put) isOperation_Operation() {}

func (*Operation_Delete) isOperation_Operation() {}

func (*Operation_Get) isOperation_Operation() {}

func (*Operation_List) isOperation_Operation() {}

func (*Operation_Scan) isOperation_Operation() {}

type Assertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_okk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{1}
}

type OperationPut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationPut) Reset() {
	*x = OperationPut{}
	mi := &file_okk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationPut) ProtoMessage() {}

func (x *OperationPut) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationPut.ProtoReflect.Descriptor instead.
func (*OperationPut) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{2}
}

func (x *OperationPut) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OperationPut) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type OperationGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationGet) Reset() {
	*x = OperationGet{}
	mi := &file_okk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationGet) ProtoMessage() {}

func (x *OperationGet) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationGet.ProtoReflect.Descriptor instead.
func (*OperationGet) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{3}
}

type OperationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationList) Reset() {
	*x = OperationList{}
	mi := &file_okk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationList) ProtoMessage() {}

func (x *OperationList) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationList.ProtoReflect.Descriptor instead.
func (*OperationList) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{4}
}

type OperationScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationScan) Reset() {
	*x = OperationScan{}
	mi := &file_okk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationScan) ProtoMessage() {}

func (x *OperationScan) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationScan.ProtoReflect.Descriptor instead.
func (*OperationScan) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{5}
}

type OperationDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationDelete) Reset() {
	*x = OperationDelete{}
	mi := &file_okk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDelete) ProtoMessage() {}

func (x *OperationDelete) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDelete.ProtoReflect.Descriptor instead.
func (*OperationDelete) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{6}
}

type ExecuteCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommand) Reset() {
	*x = ExecuteCommand{}
	mi := &file_okk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommand) ProtoMessage() {}

func (x *ExecuteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommand.ProtoReflect.Descriptor instead.
func (*ExecuteCommand) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{7}
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_okk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_okk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_okk_proto_rawDescGZIP(), []int{8}
}

var File_okk_proto protoreflect.FileDescriptor

const file_okk_proto_rawDesc = "" +
	"\n" +
	"\tokk.proto\x12\x14io.oxia.okk.proto.v1\"\x91\x03\n" +
	"\tOperation\x12B\n" +
	"\tassertion\x18\x01 \x01(\v2\x1f.io.oxia.okk.proto.v1.AssertionH\x01R\tassertion\x88\x01\x01\x126\n" +
	"\x03put\x18\x02 \x01(\v2\".io.oxia.okk.proto.v1.OperationPutH\x00R\x03put\x12?\n" +
	"\x06delete\x18\x03 \x01(\v2%.io.oxia.okk.proto.v1.OperationDeleteH\x00R\x06delete\x126\n" +
	"\x03get\x18\x04 \x01(\v2\".io.oxia.okk.proto.v1.OperationGetH\x00R\x03get\x129\n" +
	"\x04list\x18\x05 \x01(\v2#.io.oxia.okk.proto.v1.OperationListH\x00R\x04list\x129\n" +
	"\x04scan\x18\x06 \x01(\v2#.io.oxia.okk.proto.v1.OperationScanH\x00R\x04scanB\v\n" +
	"\toperationB\f\n" +
	"\n" +
	"_assertion\"\v\n" +
	"\tAssertion\"6\n" +
	"\fOperationPut\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x0e\n" +
	"\fOperationGet\"\x0f\n" +
	"\rOperationList\"\x0f\n" +
	"\rOperationScan\"\x11\n" +
	"\x0fOperationDelete\"\x10\n" +
	"\x0eExecuteCommand\"\x11\n" +
	"\x0fExecuteResponse*&\n" +
	"\x06Status\x12\x06\n" +
	"\x02Ok\x10\x00\x12\x14\n" +
	"\x10AssertionFailure\x10\x012a\n" +
	"\x03Okk\x12Z\n" +
	"\aExecute\x12$.io.oxia.okk.proto.v1.ExecuteCommand\x1a%.io.oxia.okk.proto.v1.ExecuteResponse(\x010\x01B P\x01Z\x1cgithub.com/oxia-db/okk/protob\x06proto3"

var (
	file_okk_proto_rawDescOnce sync.Once
	file_okk_proto_rawDescData []byte
)

func file_okk_proto_rawDescGZIP() []byte {
	file_okk_proto_rawDescOnce.Do(func() {
		file_okk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_okk_proto_rawDesc), len(file_okk_proto_rawDesc)))
	})
	return file_okk_proto_rawDescData
}

var file_okk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_okk_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_okk_proto_goTypes = []any{
	(Status)(0),             // 0: io.oxia.okk.proto.v1.Status
	(*Operation)(nil),       // 1: io.oxia.okk.proto.v1.Operation
	(*Assertion)(nil),       // 2: io.oxia.okk.proto.v1.Assertion
	(*OperationPut)(nil),    // 3: io.oxia.okk.proto.v1.OperationPut
	(*OperationGet)(nil),    // 4: io.oxia.okk.proto.v1.OperationGet
	(*OperationList)(nil),   // 5: io.oxia.okk.proto.v1.OperationList
	(*OperationScan)(nil),   // 6: io.oxia.okk.proto.v1.OperationScan
	(*OperationDelete)(nil), // 7: io.oxia.okk.proto.v1.OperationDelete
	(*ExecuteCommand)(nil),  // 8: io.oxia.okk.proto.v1.ExecuteCommand
	(*ExecuteResponse)(nil), // 9: io.oxia.okk.proto.v1.ExecuteResponse
}
var file_okk_proto_depIdxs = []int32{
	2, // 0: io.oxia.okk.proto.v1.Operation.assertion:type_name -> io.oxia.okk.proto.v1.Assertion
	3, // 1: io.oxia.okk.proto.v1.Operation.put:type_name -> io.oxia.okk.proto.v1.OperationPut
	7, // 2: io.oxia.okk.proto.v1.Operation.delete:type_name -> io.oxia.okk.proto.v1.OperationDelete
	4, // 3: io.oxia.okk.proto.v1.Operation.get:type_name -> io.oxia.okk.proto.v1.OperationGet
	5, // 4: io.oxia.okk.proto.v1.Operation.list:type_name -> io.oxia.okk.proto.v1.OperationList
	6, // 5: io.oxia.okk.proto.v1.Operation.scan:type_name -> io.oxia.okk.proto.v1.OperationScan
	8, // 6: io.oxia.okk.proto.v1.Okk.Execute:input_type -> io.oxia.okk.proto.v1.ExecuteCommand
	9, // 7: io.oxia.okk.proto.v1.Okk.Execute:output_type -> io.oxia.okk.proto.v1.ExecuteResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_okk_proto_init() }
func file_okk_proto_init() {
	if File_okk_proto != nil {
		return
	}
	file_okk_proto_msgTypes[0].OneofWrappers = []any{
		(*Operation_Put)(nil),
		(*Operation_Delete)(nil),
		(*Operation_Get)(nil),
		(*Operation_List)(nil),
		(*Operation_Scan)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_okk_proto_rawDesc), len(file_okk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_okk_proto_goTypes,
		DependencyIndexes: file_okk_proto_depIdxs,
		EnumInfos:         file_okk_proto_enumTypes,
		MessageInfos:      file_okk_proto_msgTypes,
	}.Build()
	File_okk_proto = out.File
	file_okk_proto_goTypes = nil
	file_okk_proto_depIdxs = nil
}
