//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OxiaCluster) DeepCopyInto(out *OxiaCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OxiaCluster.
func (in *OxiaCluster) DeepCopy() *OxiaCluster {
	if in == nil {
		return nil
	}
	out := new(OxiaCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OxiaCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OxiaClusterList) DeepCopyInto(out *OxiaClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OxiaCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OxiaClusterList.
func (in *OxiaClusterList) DeepCopy() *OxiaClusterList {
	if in == nil {
		return nil
	}
	out := new(OxiaClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OxiaClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OxiaClusterSpec) DeepCopyInto(out *OxiaClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OxiaClusterSpec.
func (in *OxiaClusterSpec) DeepCopy() *OxiaClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OxiaClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OxiaClusterStatus) DeepCopyInto(out *OxiaClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OxiaClusterStatus.
func (in *OxiaClusterStatus) DeepCopy() *OxiaClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OxiaClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicKV) DeepCopyInto(out *TCBasicKV) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicKV.
func (in *TCBasicKV) DeepCopy() *TCBasicKV {
	if in == nil {
		return nil
	}
	out := new(TCBasicKV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCBasicKV) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicKVList) DeepCopyInto(out *TCBasicKVList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCBasicKV, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicKVList.
func (in *TCBasicKVList) DeepCopy() *TCBasicKVList {
	if in == nil {
		return nil
	}
	out := new(TCBasicKVList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCBasicKVList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicKVSpec) DeepCopyInto(out *TCBasicKVSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicKVSpec.
func (in *TCBasicKVSpec) DeepCopy() *TCBasicKVSpec {
	if in == nil {
		return nil
	}
	out := new(TCBasicKVSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicKVStatus) DeepCopyInto(out *TCBasicKVStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicKVStatus.
func (in *TCBasicKVStatus) DeepCopy() *TCBasicKVStatus {
	if in == nil {
		return nil
	}
	out := new(TCBasicKVStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicSecondaryIndex) DeepCopyInto(out *TCBasicSecondaryIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicSecondaryIndex.
func (in *TCBasicSecondaryIndex) DeepCopy() *TCBasicSecondaryIndex {
	if in == nil {
		return nil
	}
	out := new(TCBasicSecondaryIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCBasicSecondaryIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicSecondaryIndexList) DeepCopyInto(out *TCBasicSecondaryIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCBasicSecondaryIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicSecondaryIndexList.
func (in *TCBasicSecondaryIndexList) DeepCopy() *TCBasicSecondaryIndexList {
	if in == nil {
		return nil
	}
	out := new(TCBasicSecondaryIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCBasicSecondaryIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicSecondaryIndexSpec) DeepCopyInto(out *TCBasicSecondaryIndexSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicSecondaryIndexSpec.
func (in *TCBasicSecondaryIndexSpec) DeepCopy() *TCBasicSecondaryIndexSpec {
	if in == nil {
		return nil
	}
	out := new(TCBasicSecondaryIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCBasicSecondaryIndexStatus) DeepCopyInto(out *TCBasicSecondaryIndexStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCBasicSecondaryIndexStatus.
func (in *TCBasicSecondaryIndexStatus) DeepCopy() *TCBasicSecondaryIndexStatus {
	if in == nil {
		return nil
	}
	out := new(TCBasicSecondaryIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataEphemeral) DeepCopyInto(out *TCMetadataEphemeral) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataEphemeral.
func (in *TCMetadataEphemeral) DeepCopy() *TCMetadataEphemeral {
	if in == nil {
		return nil
	}
	out := new(TCMetadataEphemeral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCMetadataEphemeral) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataEphemeralList) DeepCopyInto(out *TCMetadataEphemeralList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCMetadataEphemeral, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataEphemeralList.
func (in *TCMetadataEphemeralList) DeepCopy() *TCMetadataEphemeralList {
	if in == nil {
		return nil
	}
	out := new(TCMetadataEphemeralList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCMetadataEphemeralList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataEphemeralSpec) DeepCopyInto(out *TCMetadataEphemeralSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataEphemeralSpec.
func (in *TCMetadataEphemeralSpec) DeepCopy() *TCMetadataEphemeralSpec {
	if in == nil {
		return nil
	}
	out := new(TCMetadataEphemeralSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataEphemeralStatus) DeepCopyInto(out *TCMetadataEphemeralStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataEphemeralStatus.
func (in *TCMetadataEphemeralStatus) DeepCopy() *TCMetadataEphemeralStatus {
	if in == nil {
		return nil
	}
	out := new(TCMetadataEphemeralStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataNotification) DeepCopyInto(out *TCMetadataNotification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataNotification.
func (in *TCMetadataNotification) DeepCopy() *TCMetadataNotification {
	if in == nil {
		return nil
	}
	out := new(TCMetadataNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCMetadataNotification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataNotificationList) DeepCopyInto(out *TCMetadataNotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCMetadataNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataNotificationList.
func (in *TCMetadataNotificationList) DeepCopy() *TCMetadataNotificationList {
	if in == nil {
		return nil
	}
	out := new(TCMetadataNotificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCMetadataNotificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataNotificationSpec) DeepCopyInto(out *TCMetadataNotificationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataNotificationSpec.
func (in *TCMetadataNotificationSpec) DeepCopy() *TCMetadataNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(TCMetadataNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCMetadataNotificationStatus) DeepCopyInto(out *TCMetadataNotificationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCMetadataNotificationStatus.
func (in *TCMetadataNotificationStatus) DeepCopy() *TCMetadataNotificationStatus {
	if in == nil {
		return nil
	}
	out := new(TCMetadataNotificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCStreamingSequence) DeepCopyInto(out *TCStreamingSequence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCStreamingSequence.
func (in *TCStreamingSequence) DeepCopy() *TCStreamingSequence {
	if in == nil {
		return nil
	}
	out := new(TCStreamingSequence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCStreamingSequence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCStreamingSequenceList) DeepCopyInto(out *TCStreamingSequenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCStreamingSequence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCStreamingSequenceList.
func (in *TCStreamingSequenceList) DeepCopy() *TCStreamingSequenceList {
	if in == nil {
		return nil
	}
	out := new(TCStreamingSequenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCStreamingSequenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCStreamingSequenceSpec) DeepCopyInto(out *TCStreamingSequenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCStreamingSequenceSpec.
func (in *TCStreamingSequenceSpec) DeepCopy() *TCStreamingSequenceSpec {
	if in == nil {
		return nil
	}
	out := new(TCStreamingSequenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCStreamingSequenceStatus) DeepCopyInto(out *TCStreamingSequenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCStreamingSequenceStatus.
func (in *TCStreamingSequenceStatus) DeepCopy() *TCStreamingSequenceStatus {
	if in == nil {
		return nil
	}
	out := new(TCStreamingSequenceStatus)
	in.DeepCopyInto(out)
	return out
}
